name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: go test -v -timeout=60s -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Test (race)
        run: go test -v -timeout=60s -race ./...
      - name: Coverage
        uses: codecov/codecov-action@v2
      